### ISSUE TITLE
data-attributes name error

### ISSUE THREAD

**Issue by auxdesigner** [Sweefty/tinytip#1]
In your js file, line 25:
var text = obj.tooltip || ele.data('tooltip');

It should be var text = obj.tooltip || ele.data('tinytip');
Because on your demo site: it's data-tinytip="Hello There"

**Comment by mamod** [comment]
Sorry for the delay.
I'm not sure how I missed this as it's already fixed in the demo
Thank you :+1:  

fixed in dd824d7dca1085872037475c5952fba4cbd7496f
